---
bind_config_master_zones: []
bind_config_master_allow_transfer: []
bind_config_master_forwarders: []
bind_config_master_also_notify: []
bind_config_recursion: "yes"
bind_config_allow_recursion: []
bind_config_slave_zones: []
bind_config_forward_zones: []
bind_service_state: started
bind_service_enabled: yes
bind_pkg_state: installed
bind_workdir: '/var/lib/bind'
bind_log_path: '/var/log/named'
bind_masterzones_path: '{{ bind_config_basepath }}/masters'
bind_slavezones_path: '{{ bind_workdir }}/slaves'
bind_config_listen_on: ['any']
